repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-format
        name: ruff format check
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright
        entry: uv run pyright .
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
